# Initially generated by Claude Code.
"""Resolve the codex-index-aleppo DATA root, and the place this repo's CODE sits.

THIS MODULE IS DELIBERATELY TWO-ROOTED, and that is the whole point of its
existence.  Today both roots are inside this one repo -- the CODE is ``py/``, the
DATA is the twelve trees and loose files named below -- and every module here
reached the second by walking up from ``__file__`` to the first.  One expression
standing for two roots is what Phase 1 of
``../MAM-basics/doc/PLAN-evacuate-python-from-codex-index-trio.md`` exists to end:
at Phase 3 the Python leaves for MAM-basics and the data stays, so
``ac_data_root()`` becomes ``paths.sibling_repo("codex-index-aleppo")`` and nothing
else in this tree changes.

WHAT THIS DID NOT HAVE TO FIX.  Unlike book-of-job and codex-index-cam1753, no
module under ``py/`` addressed its data by a cwd-relative literal: the tree was
already cwd-independent, and only the conflation was left.  The two cwd-relative
sites this repo did have are both in ``aleppo-wiki/`` -- the entry point's four
dead ``"aleppo/..."`` literals, repointed in the same phase, and the uncalled
``mam_book_names.mam_book_path``.

WHAT IS NOT ROUTED THROUGH HERE, and why each is deliberate:

  * ``py_ac_word_image_helper/codex_page.py`` and ``flat_index.py`` compose
    ``line-breaks``, ``column-coordinates``, ``aleppo-pages`` and
    ``index-flat-annotated.json`` off roots of their own.  Both files are ONE
    COMMITTED BLOB with MAM-basics' ``py/py_ac_word_image_helper/`` copy, which
    arrived there with book-of-job in 2026-08-19, and editing either here alone
    re-forks the family the programme's Phase 0 reconciled.  Phase 0 of the trio's
    plan settles them: ``codex_page.py``'s root is a ``.git`` walk and is already
    right in both repos; ``flat_index.py``'s ``parent.parent.parent`` is right in
    both repos too and names a file only this one has.  They move at Phase 3, and
    they move together.
  * ``check_mark_order.py``, ``check_escape_sequences.py``, ``fix_mark_order.py``
    and ``fix_escape_sequences.py`` lint SOURCE, so their root is the code root,
    not this one.  All four walk up to ``.git`` already, are one committed blob
    with codex-index-cam1753's copies, and become a hand-maintained scope list at
    Phase 3 the way ``MAM-basics/py/boj_paths.py``'s ``code_paths()`` did.
  * ``py/mb_cmn/`` is vendored from MAM-basics and composes no path.
  * ``py/tests/test_h_dot_below_nfc.py``'s ``"gh-pages/"`` and its five neighbours
    are entries of ``_EXCLUDE_DIR_PREFIXES``, repo-relative prefixes matched against
    an already-scanned path.  Nothing builds a path from them; rewriting one would
    be a bug.  That module finds its own root with ``git rev-parse``.
"""

from pathlib import Path

CODE_DIR = Path(__file__).resolve().parent
"""This repo's ``py/`` -- the directory this module and the code that imports it
sit in.

Spelled off ``__file__`` rather than off ``ac_data_root() / "py"`` so that it stays
right when the code moves out from under the data, which is the whole premise of the
plan this module was written for.
"""


def ac_data_root() -> Path:
    """Path to the codex-index-aleppo corpus this code reads and writes.

    The one function that changes when the Python moves out.
    """
    return CODE_DIR.parent


def line_breaks_dir() -> Path:
    """Hand-annotated per-page word streams (35 tracked JSON), the human-in-the-loop
    output of ``py_ac_loc.gen_line_break_editor``."""
    return ac_data_root() / "line-breaks"


def col_coords_dir() -> Path:
    """Per-page column quadrilaterals (35 tracked JSON), from
    ``py_ac_loc.gen_col_quad_editor``."""
    return ac_data_root() / "column-coordinates"


def pages_dir() -> Path:
    """Aleppo Codex page scans (37 tracked JPEG), leaves 270-281 recto and verso.

    DOWNLOADED, not generated: ``download_aleppo_pages`` fetches them from
    archive.org, and no check regenerates them.
    """
    return ac_data_root() / "aleppo-pages"


def mam_xml_dir() -> Path:
    """Vendored MAM-XML snapshot (24 tracked XML), the word-sequence ground truth --
    see ``doc/reading-mam-simple.md``."""
    return ac_data_root() / "MAM-XML"


def ds_flat_stream_dir() -> Path:
    """Derived per-page flat streams (8 tracked JSON) from
    ``py_ac_loc.gen_flat_stream``."""
    return ac_data_root() / "ds-flat-stream"


def plot_col_coords_out_dir() -> Path:
    """The three tracked PNGs ``py_ac_loc.plot_col_coords`` keeps, as against the
    throwaway copies it also writes into ``novc_dir()``."""
    return ac_data_root() / "plot_col_coords-out"


def novc_dir() -> Path:
    """Gitignored scratch tree, where the two editors and the word previewer write
    the HTML they open in a browser."""
    return ac_data_root() / ".novc"


def wiki_dir() -> Path:
    """``aleppo-wiki/`` -- J David Stark's index, its three derived artifacts, and the
    hand-corrected ``index-flat-corrected.json`` that ``gen_index_flat_annotated``
    reads.

    Its own pipeline addresses it off ``__file__`` instead, that code sitting inside
    this directory; this accessor is for ``py/``, which sits outside it.
    """
    return ac_data_root() / "aleppo-wiki"


def flat_index_corrected_path() -> Path:
    """Hand-corrected flat index (``<wiki_dir>/index-flat-corrected.json``).

    Written by no program: it is ``index-flat.json`` with corrections applied by
    hand, and it is the input to ``gen_index_flat_annotated``.
    """
    return wiki_dir() / "index-flat-corrected.json"


def flat_index_annotated_path() -> Path:
    """Annotated flat index (``<data_root>/index-flat-annotated.json``), written by
    ``gen_index_flat_annotated`` and read by ``py_ac_word_image_helper.flat_index``."""
    return ac_data_root() / "index-flat-annotated.json"


def check_line_breaks_html_path() -> Path:
    """The line-break check's HTML report (``<data_root>/check_line_breaks.html``),
    tracked, and rewritten by every run of ``py_ac_loc.check_line_breaks``."""
    return ac_data_root() / "check_line_breaks.html"


def word_finding_test_data_path() -> Path:
    """``<data_root>/test-data-from-book-of-job.json`` -- the minimal extract of
    book-of-job's enriched quirk records that ``check_word_finding`` runs against."""
    return ac_data_root() / "test-data-from-book-of-job.json"
