# Initially generated by GitHub Copilot.
"""Download Aleppo Codex page images (leaves 270–281) from archive.org.

Downloads the 24 page images (recto and verso for each leaf) into the
aleppo-pages/ directory, skipping any that already exist.

Usage:
    python download_aleppo_pages.py
"""

import os
from urllib.request import Request, urlopen

from mb_cmn.url_percent import pct_path_component

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "aleppo-pages")
os.makedirs(OUT_DIR, exist_ok=True)


def _leaf_to_page_n(page_id):
    """Convert a leaf ID like '270r' to the archive.org 0-based page index."""
    num = int(page_id[:-1])
    side = page_id[-1]
    return (num - 1) * 2 + 2 + (0 if side == "r" else 1)


_ZIP_MEMBER = "/7/items/aleppo-codex/Aleppo Codex_jp2.zip"


def _archive_image_url(page):
    zip_part = pct_path_component(_ZIP_MEMBER, safe="/")
    file_member = f"Aleppo Codex_jp2/Aleppo Codex_{page:04d}.jp2"
    file_part = pct_path_component(file_member, safe="/")
    return (
        "https://ia601801.us.archive.org/BookReader/BookReaderImages.php"
        f"?zip={zip_part}&file={file_part}&id=aleppo-codex&scale=2&rotate=0"
    )


# Leaves 270–281, recto and verso
PAGE_IDS = []
for leaf in range(270, 282):
    PAGE_IDS.append(f"{leaf}r")
    PAGE_IDS.append(f"{leaf}v")

for page_id in PAGE_IDS:
    n = _leaf_to_page_n(page_id)
    url = _archive_image_url(n)
    out_path = os.path.join(OUT_DIR, f"{page_id}.jpg")
    if os.path.exists(out_path):
        print(f"  Already exists: {out_path}")
        continue
    print(f"  Downloading {page_id} (archive page {n}) ...")
    req = Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urlopen(req, timeout=120) as resp:
        data = resp.read()
    with open(out_path, "wb") as f:
        f.write(data)
    print(f"    Saved {len(data)} bytes -> {out_path}")

print("Done.")
