# Initially generated by Claude Code.
"""Generate a Claude Code permission glob for a given Bash command.

This script assumes that in Claude Code's permission system ``*`` does
not match ``/`` (pathlib/gitignore-style).  This is NOT confirmed — it
is equally possible that ``*`` matches ``/`` (fnmatch-style).  See
``../masorah-books/.claude/test_globs.py`` which tests the same set of
globs under both assumptions and shows where they diverge.  (That repo
was ``yeivin-itm`` until it was renamed on 2026-07-31.)

Under the "strict" assumption, this script identifies path-like
segments in a command and replaces them with directory-preserving
patterns (e.g. ``.novc/*``), while replacing other variable parts
(numbers, specific filenames) with ``*``.

Usage
-----
    python gen_permission_glob.py '<command>'

Example
-------
    $ python gen_permission_glob.py 'gh issue close 19 --comment "$(cat .novc/issue_comment_19.md)"'
    Bash(gh issue close * --comment "$(cat .novc/*)")

The output can be pasted directly into .claude/settings.json allow list.
"""

import re
import sys


def _glob_for_token(token):
    """Return a glob pattern for a single shell token.

    Heuristics:
    - Pure digits -> *
    - Looks like a path (contains /) -> keep directory part, glob the filename
    - Otherwise -> leave literal
    """
    # Pure number (like an issue number)
    if re.fullmatch(r"\d+", token):
        return "*"

    # Path-like: contains /
    if "/" in token:
        # Split into directory + basename
        last_slash = token.rfind("/")
        directory = token[: last_slash + 1]  # includes trailing /
        basename = token[last_slash + 1 :]

        # Glob the basename (the specific filename)
        if basename:
            return directory + "*"
        else:
            # Trailing slash only, e.g. ".novc/"
            return token

    return token


def generate_glob(command):
    """Generate a permission glob string for the given command."""
    # We need to handle quoting carefully.  Rather than a full shell parser,
    # we walk the command character by character, tracking quote state, and
    # split on unquoted whitespace.  Within each token we apply _glob_for_token
    # to unquoted sub-segments that look like they should be abstracted.

    # Strategy: find "interesting" sub-strings to glob within the raw command.
    # 1. Replace bare integers delimited by whitespace or quote boundaries.
    # 2. Replace path basenames (the part after the last /) inside known patterns.

    result = command

    # Replace bare integers (whole tokens that are just digits)
    # Match digits surrounded by whitespace or start/end of string
    result = re.sub(r"(?<=\s)\d+(?=\s|$|\")", "*", result)
    result = re.sub(r"^(\d+)(?=\s)", "*", result)

    # Replace filenames in paths: keep the directory, glob the basename.
    # Match patterns like: some/path/filename.ext
    # But be careful to only glob the basename part.
    def _glob_path_basename(m):
        prefix = m.group(1)  # everything up to and including last /
        return prefix + "*"

    # Match a path segment: directory/ followed by a filename with extension
    result = re.sub(r"(\.\w[\w.-]*/)([\w][\w.-]*\.[\w]+)", _glob_path_basename, result)

    return f"Bash({result})"


def main():
    if len(sys.argv) < 2:
        print("Usage: python gen_permission_glob.py '<command>'", file=sys.stderr)
        sys.exit(1)

    command = sys.argv[1]
    glob_pattern = generate_glob(command)
    print(glob_pattern)


if __name__ == "__main__":
    main()
