# Initially generated by Claude Code.
"""Entrypoint wrapper for py_ac_loc.gen_line_break_editor.

Added 2026-08-22 by Phase 1 of
``../MAM-basics/doc/PLAN-evacuate-python-from-codex-index-trio.md``, one of five that
bring every runnable module of ``py_ac_loc/`` under a wrapper.  That phase gave the
package its data paths through ``ac_paths``, which sits at the top of ``py/`` and so
is importable only when ``py/`` is ``sys.path[0]``.  A wrapper here makes that so;
``python py/py_ac_loc/gen_line_break_editor.py`` does not, putting ``py/py_ac_loc/`` there
instead.  The three wrappers that already existed --
``main_check_line_breaks.py``, ``main_gen_flat_stream.py`` and
``main_gen_lb_flat_stream.py`` -- were written for the same reason in its earlier
form: those three modules import a sibling as ``py_ac_loc.<name>``, so they had
stopped being directly runnable long before this.
"""

from py_ac_loc.gen_line_break_editor import main

if __name__ == "__main__":
    main()
