# Initially generated by Claude Code.
"""Look up page IDs from index-flat-annotated.json."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FLAT_INDEX_PATH = ROOT / "index-flat-annotated.json"


def find_pages_in_flat_index(book, ch, v):
    """Return a list of de_leaf page IDs whose text range contains (book, ch, v).

    Uses index-flat-annotated.json as the data source.  Raises KeyError if the
    book is not in the codex's book list.
    """
    with open(FLAT_INDEX_PATH, encoding="utf-8") as f:
        data = json.load(f)
    book_order = {b: i for i, b in enumerate(data["header"]["books"])}

    target = (book_order[book], ch, v)
    result = []
    for rec in data["body"]:
        s = rec["de_text_range"][0]
        e = rec["de_text_range"][1]
        start = (book_order[s[0]], s[1], s[2])
        end = (book_order[e[0]], e[1], e[2])
        if start <= target <= end:
            result.append(rec["de_leaf"])
    return result
