# Initially generated by GitHub Copilot.
"""Aleppo Codex page utilities: index, local image loading, bounding boxes."""

import json
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LB_DIR = ROOT / "line-breaks"
CC_DIR = ROOT / "column-coordinates"
IMG_DIR = ROOT / "aleppo-pages"

LINES_PER_COL = 28

_PAGE_RE = re.compile(r"^(\d+[rv])\.json$")


def _leaf_to_page_n(page_id):
    num = int(page_id[:-1])
    side = page_id[-1]
    return (num - 1) * 2 + 2 + (0 if side == "r" else 1)


def local_image_path(page_id):
    """Return the absolute Path to the local image for *page_id*."""
    return IMG_DIR / f"{page_id}.jpg"


def image_relpath(page_id):
    """Return a relative path suitable for HTML generated into .novc/."""
    return f"../aleppo-pages/{page_id}.jpg"


def _parse_verse_label(label):
    """Parse 'Job 38:31' into (book, chapter, verse)."""
    parts = label.split(" ", 1)
    cv = parts[1].split(":")
    return parts[0], int(cv[0]), int(cv[1])


def _page_verse_range(path):
    """Extract (first_ref, last_ref) from a line-break JSON file.

    Each ref is (book, chapter, verse).  Returns None if the file
    has no verse markers.
    """
    data = json.loads(path.read_text("utf-8"))
    first = None
    last = None
    for item in data:
        if isinstance(item, dict):
            for key in ("verse-start", "verse-fragment-start"):
                if key in item:
                    ref = _parse_verse_label(item[key])
                    if first is None:
                        first = ref
                    last = ref
    if first is None:
        return None
    # last ref from verse-end / verse-fragment-end (for the end boundary)
    for item in reversed(data):
        if isinstance(item, dict):
            for key in ("verse-end", "verse-fragment-end"):
                if key in item:
                    last = _parse_verse_label(item[key])
                    break
            else:
                continue
            break
    return first, last


def load_index(book="Job"):
    """Load page index for *book* by scanning line-break files.

    Returns a list of ``(leaf, ch_start, v_start, ch_end, v_end)``
    tuples for every page that contains (even partially) the
    requested book.  Cross-book boundary pages are clamped so that
    the chapter:verse range covers only the requested book's
    portion.
    """
    pages = []
    for path in sorted(LB_DIR.glob("*.json")):
        m = _PAGE_RE.match(path.name)
        if not m:
            continue
        leaf = m.group(1)
        result = _page_verse_range(path)
        if result is None:
            continue
        first_ref, last_ref = result
        # Skip pages that don't mention our book at all
        if first_ref[0] != book and last_ref[0] != book:
            continue
        # Clamp to our book
        if first_ref[0] == book:
            ch_s, v_s = first_ref[1], first_ref[2]
        else:
            ch_s, v_s = 1, 1
        if last_ref[0] == book:
            ch_e, v_e = last_ref[1], last_ref[2]
        else:
            ch_e, v_e = 99, 99
        pages.append((leaf, ch_s, v_s, ch_e, v_e))
    return pages


def find_page_for_verse(pages, ch, v):
    """Find which page a verse is on (returns the first matching page)."""
    result = find_pages_for_verse(pages, ch, v)
    return result[0] if result else None


def find_pages_for_verse(pages, ch, v):
    """Find *all* pages that contain a given verse.

    Returns a list of page-id strings, ordered as they appear in the
    codex index.  A verse that spans a page boundary will appear in
    multiple pages.  Returns an empty list if the verse is not found.
    """
    result = []
    for leaf, ch_s, v_s, ch_e, v_e in pages:
        # Strict containment: verse starts on or after page start
        # and strictly before page end.
        start_ok = (ch, v) >= (ch_s, v_s)
        end_ok = (ch, v) < (ch_e, v_e)
        if start_ok and end_ok:
            result.append(leaf)
            continue
        # Boundary case: verse is exactly at the page end.
        if (ch, v) >= (ch_s, v_s) and (ch, v) <= (ch_e, v_e):
            result.append(leaf)
    return result


def _col_key_from_spec(col_spec):
    """Convert a NofM col spec (e.g. '1of2') or plain int to a column key."""
    if isinstance(col_spec, int):
        return f"col{col_spec}"
    if "of" in str(col_spec):
        return f"col{str(col_spec).split('of')[0]}"
    return f"col{col_spec}"


def _image_size(cc):
    """Extract (width, height) from a column-coordinates dict."""
    sz = cc["image_size"]
    if isinstance(sz, list):
        return sz[0], sz[1]
    return sz["width"], sz["height"]


def _line_dividers(n_lines):
    """Compute t values (0–1) for dividers between n_lines line boxes.

    Uses weighted spacing: top line = 1.5x, bottom line = 1.25x,
    middle lines = 1x.  This accounts for lamed ascenders at top and
    descenders at bottom of the column.

    Returns a list of n_lines+1 values: dividers[0]=0, dividers[n_lines]=1.
    Line i (1-based) spans dividers[i-1] to dividers[i].
    """
    top_weight = 1.5
    bot_weight = 1.25
    mid_count = n_lines - 2
    total = top_weight + mid_count + bot_weight
    dividers = [0.0]
    for i in range(n_lines):
        w = top_weight if i == 0 else (bot_weight if i == n_lines - 1 else 1.0)
        dividers.append(dividers[-1] + w / total)
    return dividers


def get_line_bbox(page_id, col, line_num, buffer_lines=2, margin_factor=0.05):
    """Get pixel bounding box for a line, with buffer lines above and below.

    *col* may be a NofM string (e.g. ``'1of2'``) or an integer.

    *margin_factor* controls horizontal padding as a fraction of column
    width (default 0.05 = 5%).  Use a larger value (e.g. 0.40) to
    capture masorah parva notes in the page margins.
    """
    cc_path = CC_DIR / f"{page_id}.json"
    with open(cc_path, encoding="utf-8") as f:
        cc = json.load(f)

    col_key = _col_key_from_spec(col)
    px = cc["columns"][col_key]["px"]
    img_w, img_h = _image_size(cc)

    tl = px["tl"]
    tr = px["tr"]
    bl = px["bl"]
    br = px["br"]

    # Column bounding box
    col_left = min(tl[0], bl[0])
    col_right = max(tr[0], br[0])
    col_top = min(tl[1], tr[1])
    col_bot = max(bl[1], br[1])
    col_w = col_right - col_left
    col_h = col_bot - col_top

    # Weighted line dividers
    dividers = _line_dividers(LINES_PER_COL)

    # Target line spans dividers[line_num-1] to dividers[line_num]
    t_top = dividers[line_num - 1]
    t_bot = dividers[line_num]
    line_top = col_top + t_top * col_h
    line_bot = col_top + t_bot * col_h
    line_spacing = line_bot - line_top

    # Buffer uses the average line height (col_h / LINES_PER_COL)
    avg_ls = col_h / LINES_PER_COL
    crop_top = max(0, line_top - buffer_lines * avg_ls)
    crop_bot = min(img_h, line_bot + buffer_lines * avg_ls)

    # Horizontal extent with margin
    margin_x = int(col_w * margin_factor)
    crop_left = max(0, col_left - margin_x)
    crop_right = min(img_w, col_right + margin_x)

    return (
        int(crop_left),
        int(crop_top),
        int(crop_right),
        int(crop_bot),
        int(line_top - crop_top),  # target line offset from crop top
        int(line_spacing),  # line spacing in px
    )


def load_page_image(page_id):
    """Load a page image from the local aleppo-pages/ directory.

    Returns a PIL Image.  Exits with an error if the file is missing
    (run download_aleppo_pages.py first).
    """
    path = local_image_path(page_id)
    if not path.exists():
        print(f"  ERROR: image not found: {path}")
        print("  Run download_aleppo_pages.py to fetch the images.")
        sys.exit(1)
    return Image.open(path)
