# Initially generated by GitHub Copilot.
"""Aleppo Codex page utilities: index, local image loading, bounding boxes."""

import json
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LB_DIR = ROOT / "line-breaks"
CC_DIR = ROOT / "column-coordinates"
IMG_DIR = ROOT / "aleppo-pages"

_PAGE_RE = re.compile(r"^(\d+[rv])\.json$")


def _leaf_to_page_n(page_id):
    num = int(page_id[:-1])
    side = page_id[-1]
    return (num - 1) * 2 + 2 + (0 if side == "r" else 1)


def local_image_path(page_id):
    """Return the absolute Path to the local image for *page_id*."""
    return IMG_DIR / f"{page_id}.jpg"


def image_relpath(page_id):
    """Return a relative path suitable for HTML generated into .novc/."""
    return f"../aleppo-pages/{page_id}.jpg"


def _parse_verse_label(label):
    """Parse 'Job 38:31' into (book, chapter, verse)."""
    parts = label.split(" ", 1)
    cv = parts[1].split(":")
    return parts[0], int(cv[0]), int(cv[1])


def _page_verse_range(path):
    """Extract (first_ref, last_ref) from a line-break JSON file.

    Each ref is (book, chapter, verse).  Returns None if the file
    has no verse markers.
    """
    data = json.loads(path.read_text("utf-8"))
    first = None
    last = None
    for item in data:
        if isinstance(item, dict):
            for key in ("verse-start", "verse-fragment-start"):
                if key in item:
                    ref = _parse_verse_label(item[key])
                    if first is None:
                        first = ref
                    last = ref
    if first is None:
        return None
    # last ref from verse-end / verse-fragment-end (for the end boundary)
    for item in reversed(data):
        if isinstance(item, dict):
            for key in ("verse-end", "verse-fragment-end"):
                if key in item:
                    last = _parse_verse_label(item[key])
                    break
            else:
                continue
            break
    return first, last


def load_index(book="Job"):
    """Load page index for *book* by scanning line-break files.

    Returns a list of ``(leaf, ch_start, v_start, ch_end, v_end)``
    tuples for every page that contains (even partially) the
    requested book.  Cross-book boundary pages are clamped so that
    the chapter:verse range covers only the requested book's
    portion.
    """
    pages = []
    for path in sorted(LB_DIR.glob("*.json")):
        m = _PAGE_RE.match(path.name)
        if not m:
            continue
        leaf = m.group(1)
        result = _page_verse_range(path)
        if result is None:
            continue
        first_ref, last_ref = result
        # Skip pages that don't mention our book at all
        if first_ref[0] != book and last_ref[0] != book:
            continue
        # Clamp to our book
        if first_ref[0] == book:
            ch_s, v_s = first_ref[1], first_ref[2]
        else:
            ch_s, v_s = 1, 1
        if last_ref[0] == book:
            ch_e, v_e = last_ref[1], last_ref[2]
        else:
            ch_e, v_e = 99, 99
        pages.append((leaf, ch_s, v_s, ch_e, v_e))
    return pages


def find_page_for_verse(pages, ch, v):
    """Find which page a verse is on (returns the first matching page)."""
    result = find_pages_for_verse(pages, ch, v)
    return result[0] if result else None


def find_pages_for_verse(pages, ch, v):
    """Find *all* pages that contain a given verse.

    Returns a list of page-id strings, ordered as they appear in the
    codex index.  A verse that spans a page boundary will appear in
    multiple pages.  Returns an empty list if the verse is not found.
    """
    result = []
    for leaf, ch_s, v_s, ch_e, v_e in pages:
        # Strict containment: verse starts on or after page start
        # and strictly before page end.
        start_ok = (ch, v) >= (ch_s, v_s)
        end_ok = (ch, v) < (ch_e, v_e)
        if start_ok and end_ok:
            result.append(leaf)
            continue
        # Boundary case: verse is exactly at the page end.
        if (ch, v) >= (ch_s, v_s) and (ch, v) <= (ch_e, v_e):
            result.append(leaf)
    return result


def get_line_bbox(page_id, col, line_num, buffer_lines=2, margin_factor=0.05):
    """Get pixel bounding box for a line, with buffer lines above and below.

    *margin_factor* controls horizontal padding as a fraction of column
    width (default 0.05 = 5%).  Use a larger value (e.g. 0.40) to
    capture masorah parva notes in the page margins.
    """
    cc_path = CC_DIR / f"{page_id}.json"
    with open(cc_path, encoding="utf-8") as f:
        cc = json.load(f)

    col_key = f"col{col}"
    col_data = cc["columns"][col_key]["px"]
    img_w = cc["image_size"]["width"]
    img_h = cc["image_size"]["height"]

    x = col_data["x"]
    y = col_data["y"]
    w = col_data["w"]
    ls = col_data["line_spacing"]

    # Target line top and bottom
    line_top = y + (line_num - 1) * ls
    line_bot = line_top + ls

    # Add buffer
    crop_top = max(0, line_top - buffer_lines * ls)
    crop_bot = min(img_h, line_bot + buffer_lines * ls)

    # Expand horizontally a bit beyond the column
    margin_x = int(w * margin_factor)
    crop_left = max(0, x - margin_x)
    crop_right = min(img_w, x + w + margin_x)

    return (
        int(crop_left),
        int(crop_top),
        int(crop_right),
        int(crop_bot),
        int(line_top - crop_top),  # target line offset from crop top
        int(ls),  # line spacing in px
    )


def load_page_image(page_id):
    """Load a page image from the local aleppo-pages/ directory.

    Returns a PIL Image.  Exits with an error if the file is missing
    (run download_aleppo_pages.py first).
    """
    path = local_image_path(page_id)
    if not path.exists():
        print(f"  ERROR: image not found: {path}")
        print("  Run download_aleppo_pages.py to fetch the images.")
        sys.exit(1)
    return Image.open(path)
