# Initially generated by Claude Code.
"""
Generate an interactive HTML editor for adjusting column bounding
quadrilaterals on an Aleppo Codex page image.

Shows the page image with draggable quadrilaterals (one per column).
Each quad has 4 freely-movable corners. 28 evenly-spaced lines are
interpolated within each quad. Export produces JSON with corner
coordinates (both relative and pixel).

Supports 2-column (poetic, e.g. Job) and 3-column (prose, e.g. Deut)
layouts via the ncols argument.

Usage:
    .venv\\Scripts\\python.exe py_ac_loc/gen_col_quad_editor.py 270r
    .venv\\Scripts\\python.exe py_ac_loc/gen_col_quad_editor.py 001v 3
"""

import functools
import http.server
import json
import socket
import sys
import threading
import webbrowser

from PIL import Image

import ac_paths

OUT_DIR = ac_paths.novc_dir()
COORD_DIR = ac_paths.col_coords_dir()
IMG_DIR = ac_paths.pages_dir()

LINES_PER_COL = 28


def serve_and_open(directory, filename):
    """Start an HTTP server in *directory*, open *filename* in the browser,
    and block until Ctrl+C."""
    handler = functools.partial(
        http.server.SimpleHTTPRequestHandler, directory=str(directory)
    )
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        port = s.getsockname()[1]
    server = http.server.HTTPServer(("127.0.0.1", port), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    url = f"http://127.0.0.1:{port}/{filename}"
    print(f"Serving at http://127.0.0.1:{port}/ — opening {url}")
    print("Press Ctrl+C to stop.")
    webbrowser.open(url)
    try:
        thread.join()
    except KeyboardInterrupt:
        print("\nShutting down server.")
        server.shutdown()


def _average_saved_quads(is_recto, ncols):
    """Average the rel coords of all saved quads for the same page type and ncols."""
    col_keys = [f"col{i}" for i in range(1, ncols + 1)]
    matching = []
    for f in COORD_DIR.glob("*.json"):
        pid = f.stem
        if (pid.endswith("r")) != is_recto:
            continue
        data = json.loads(f.read_text(encoding="utf-8"))
        # Only include files with the same number of columns
        if len(data["columns"]) != ncols:
            continue
        # Skip files that don't have quad-format corners
        first_col = next(iter(data["columns"].values()))
        first_rel = first_col.get("rel", first_col)
        if "tl" not in first_rel:
            continue
        cols = {}
        for col_key in col_keys:
            if col_key not in data["columns"]:
                break
            src = data["columns"][col_key]
            rel = src.get("rel", src)
            cols[col_key] = {c: rel[c] for c in ("tl", "tr", "bl", "br")}
        else:
            matching.append(cols)
    if not matching:
        return None
    avg = {}
    for col_key in col_keys:
        avg[col_key] = {}
        for corner in ("tl", "tr", "bl", "br"):
            xs = [m[col_key][corner][0] for m in matching]
            ys = [m[col_key][corner][1] for m in matching]
            avg[col_key][corner] = [
                round(sum(xs) / len(xs), 4),
                round(sum(ys) / len(ys), 4),
            ]
    return avg


def _load_defaults(page_id, ncols):
    """Load saved quad coordinates if they exist, else use averaged defaults."""
    col_keys = [f"col{i}" for i in range(1, ncols + 1)]

    coord_file = COORD_DIR / f"{page_id}.json"
    if coord_file.exists():
        data = json.loads(coord_file.read_text(encoding="utf-8"))
        first_col = next(iter(data["columns"].values()))
        first_rel = first_col.get("rel", first_col)
        if "tl" in first_rel and len(data["columns"]) == ncols:
            cols = {}
            for col_key in col_keys:
                src = data["columns"][col_key]
                rel = src.get("rel", src)
                cols[col_key] = {
                    "tl": rel["tl"],
                    "tr": rel["tr"],
                    "bl": rel["bl"],
                    "br": rel["br"],
                }
            return {"page": page_id, "columns": cols}, True

    is_recto = page_id.endswith("r")

    avg = _average_saved_quads(is_recto, ncols)
    if avg:
        return {"page": page_id, "columns": avg}, False

    # Hardcoded fallback — RTL reading order: col1 = rightmost column
    if ncols == 1:
        defaults = {
            "col1": {
                "tl": [0.08, 0.09],
                "tr": [0.92, 0.09],
                "bl": [0.08, 0.82],
                "br": [0.92, 0.82],
            },
        }
    elif ncols == 2:
        if is_recto:
            defaults = {
                "col1": {
                    "tl": [0.55, 0.09],
                    "tr": [0.93, 0.09],
                    "bl": [0.55, 0.82],
                    "br": [0.93, 0.82],
                },
                "col2": {
                    "tl": [0.08, 0.09],
                    "tr": [0.46, 0.09],
                    "bl": [0.08, 0.82],
                    "br": [0.46, 0.82],
                },
            }
        else:
            defaults = {
                "col1": {
                    "tl": [0.55, 0.09],
                    "tr": [0.93, 0.09],
                    "bl": [0.55, 0.82],
                    "br": [0.93, 0.82],
                },
                "col2": {
                    "tl": [0.08, 0.09],
                    "tr": [0.46, 0.09],
                    "bl": [0.08, 0.82],
                    "br": [0.46, 0.82],
                },
            }
    else:
        # 3-column layout
        if is_recto:
            defaults = {
                "col1": {
                    "tl": [0.68, 0.09],
                    "tr": [0.96, 0.09],
                    "bl": [0.68, 0.82],
                    "br": [0.96, 0.82],
                },
                "col2": {
                    "tl": [0.36, 0.09],
                    "tr": [0.64, 0.09],
                    "bl": [0.36, 0.82],
                    "br": [0.64, 0.82],
                },
                "col3": {
                    "tl": [0.04, 0.09],
                    "tr": [0.32, 0.09],
                    "bl": [0.04, 0.82],
                    "br": [0.32, 0.82],
                },
            }
        else:
            defaults = {
                "col1": {
                    "tl": [0.68, 0.09],
                    "tr": [0.96, 0.09],
                    "bl": [0.68, 0.82],
                    "br": [0.96, 0.82],
                },
                "col2": {
                    "tl": [0.36, 0.09],
                    "tr": [0.64, 0.09],
                    "bl": [0.36, 0.82],
                    "br": [0.64, 0.82],
                },
                "col3": {
                    "tl": [0.04, 0.09],
                    "tr": [0.32, 0.09],
                    "bl": [0.04, 0.82],
                    "br": [0.32, 0.82],
                },
            }
    return {"page": page_id, "columns": defaults}, False


def generate_editor(page_id, ncols=2):
    """Generate the HTML quad editor for a page."""
    img_path = IMG_DIR / f"{page_id}.jpg"
    if not img_path.exists():
        print(f"Error: image not found: {img_path}")
        sys.exit(1)

    with Image.open(img_path) as im:
        img_w, img_h = im.size

    # Image URL relative to repo root (served via HTTP)
    img_url = f"/aleppo-pages/{page_id}.jpg"

    data, from_file = _load_defaults(page_id, ncols)
    col_keys = [f"col{i}" for i in range(1, ncols + 1)]
    source_note = (
        f"column-coordinates/{page_id}.json"
        if from_file
        else "averaged from saved pages"
    )

    # Build JS defaults object
    defaults_entries = []
    for col_key in col_keys:
        c = data["columns"][col_key]
        defaults_entries.append(
            f"  {col_key}: {{\n"
            f"    tl: [{c['tl'][0]}, {c['tl'][1]}],\n"
            f"    tr: [{c['tr'][0]}, {c['tr'][1]}],\n"
            f"    bl: [{c['bl'][0]}, {c['bl'][1]}],\n"
            f"    br: [{c['br'][0]}, {c['br'][1]}],\n"
            f"  }}"
        )
    defaults_js = "{\n" + ",\n".join(defaults_entries) + ",\n}"

    # Colours for up to 3 columns
    _all_colours = [
        "rgba(255, 70, 70, 0.8)",
        "rgba(70, 140, 255, 0.8)",
        "rgba(70, 200, 70, 0.8)",
    ]
    _all_fills = [
        "rgba(255, 70, 70, 0.06)",
        "rgba(70, 140, 255, 0.06)",
        "rgba(70, 200, 70, 0.06)",
    ]
    _all_handle_fills = ["#f44", "#48f", "#4c4"]
    col_colours_js = json.dumps(_all_colours[:ncols])
    col_fills_js = json.dumps(_all_fills[:ncols])
    col_handle_fills_js = json.dumps(_all_handle_fills[:ncols])

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Column Quad Editor — {page_id}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: #222;
    color: #eee;
    font-family: system-ui, sans-serif;
    overflow: hidden;
  }}
  #toolbar {{
    position: fixed;
    top: 0; left: 0; right: 0;
    height: 40px;
    background: #333;
    display: flex;
    align-items: center;
    padding: 0 12px;
    gap: 10px;
    z-index: 100;
    font-size: 13px;
  }}
  #toolbar button {{
    padding: 4px 12px;
    cursor: pointer;
    border: 1px solid #666;
    background: #444;
    color: #eee;
    border-radius: 3px;
    font-size: 13px;
  }}
  #toolbar button:hover {{ background: #555; }}
  #toolbar button.active {{ background: #070; border-color: #0a0; }}
  .info {{ color: #aaa; font-size: 12px; }}
  #container {{
    position: absolute;
    top: 40px; left: 0; right: 0; bottom: 0;
    overflow: auto;
  }}
  #page-wrapper {{
    position: relative;
    display: block;
    width: fit-content;
    margin: 0 auto;
  }}
  #page-wrapper img {{
    display: block;
    height: calc(100vh - 40px);
    width: auto;
  }}
  #overlay {{
    position: absolute;
    top: 0; left: 0; right: 0; bottom: 0;
    pointer-events: none;
  }}
  #overlay svg {{
    width: 100%;
    height: 100%;
  }}
  .handle {{
    pointer-events: all;
    cursor: grab;
  }}
  .handle:hover {{ opacity: 1; }}
  .handle.dragging {{ cursor: grabbing; }}
  .toast {{
    position: fixed;
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
    background: #070;
    color: #fff;
    padding: 8px 24px;
    border-radius: 4px;
    font-size: 14px;
    z-index: 200;
    opacity: 0;
    transition: opacity 0.3s;
  }}
  .toast.show {{ opacity: 1; }}
</style>
</head>
<body>

<div id="toolbar">
  <span><b>Quad Editor</b> — {page_id} ({ncols}-col)</span>
  <button id="fine-btn" onclick="toggleFine()" class="active">Fine: ON</button>
  <button onclick="resetPositions()">Reset</button>
  <button onclick="exportJSON()" style="background:#046;border-color:#08f">Export JSON</button>
  <span class="info">Source: {source_note} | Image: {img_w}×{img_h}</span>
  <span class="info" id="status" style="margin-left:auto"></span>
</div>

<div id="container">
  <div id="page-wrapper">
    <img id="page-img" src="{img_url}" alt="Page {page_id}">
    <div id="overlay">
      <svg id="svg" viewBox="0 0 1 1" preserveAspectRatio="none"></svg>
    </div>
  </div>
</div>

<div id="toast" class="toast"></div>

<script>
"use strict";

const PAGE = "{page_id}";
const IMG_W = {img_w};
const IMG_H = {img_h};
const N_LINES = {LINES_PER_COL};
const N_COLS = {ncols};
const FINE_SCALE = 0.15;

const COL_COLOURS = {col_colours_js};
const COL_FILLS = {col_fills_js};
const COL_HANDLE_FILLS = {col_handle_fills_js};

const DEFAULTS = {defaults_js};

let cols = JSON.parse(JSON.stringify(DEFAULTS));
let fineMode = true;

const svg = document.getElementById('svg');
const statusEl = document.getElementById('status');
const toastEl = document.getElementById('toast');

function toggleFine() {{
  fineMode = !fineMode;
  const btn = document.getElementById('fine-btn');
  btn.textContent = fineMode ? 'Fine: ON' : 'Fine: OFF';
  btn.classList.toggle('active', fineMode);
}}

function resetPositions() {{
  cols = JSON.parse(JSON.stringify(DEFAULTS));
  drawAll();
}}

function showToast(msg) {{
  toastEl.textContent = msg;
  toastEl.classList.add('show');
  setTimeout(() => toastEl.classList.remove('show'), 2000);
}}

// Bilinear interpolation within the quad for line endpoints.
// t = 0 at top edge, t = 1 at bottom edge.
function lineEndpoints(q, t) {{
  return {{
    left:  [q.tl[0] + t * (q.bl[0] - q.tl[0]),
            q.tl[1] + t * (q.bl[1] - q.tl[1])],
    right: [q.tr[0] + t * (q.br[0] - q.tr[0]),
            q.tr[1] + t * (q.br[1] - q.tr[1])],
  }};
}}

function drawAll() {{
  while (svg.firstChild) svg.removeChild(svg.firstChild);

  const colKeys = Object.keys(cols);
  colKeys.forEach((colName, ci) => {{
    const q = cols[colName];
    const colNum = ci + 1;
    const colour = COL_COLOURS[ci];
    const fillColour = COL_FILLS[ci];
    const handleFill = COL_HANDLE_FILLS[ci];

    // Quad outline (filled lightly)
    const poly = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
    const pts = [q.tl, q.tr, q.br, q.bl].map(p => p.join(',')).join(' ');
    poly.setAttribute('points', pts);
    poly.setAttribute('fill', fillColour);
    poly.setAttribute('stroke', colour);
    poly.setAttribute('stroke-width', '0.002');
    poly.setAttribute('stroke-dasharray', '0.008 0.004');
    svg.appendChild(poly);

    // Variable line heights: top line = 1.5x, bottom = 1.25x, middle = 1x
    const TOP_WEIGHT = 1.5;
    const BOT_WEIGHT = 1.25;
    const MID_COUNT = N_LINES - 2;
    const totalWeight = TOP_WEIGHT + MID_COUNT + BOT_WEIGHT;

    const dividerT = [0];
    for (let i = 0; i < N_LINES; i++) {{
      const w = i === 0 ? TOP_WEIGHT : i === N_LINES - 1 ? BOT_WEIGHT : 1;
      dividerT.push(dividerT[i] + w / totalWeight);
    }}

    for (let i = 1; i < N_LINES; i++) {{
      const t = dividerT[i];
      const ep = lineEndpoints(q, t);
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      line.setAttribute('x1', ep.left[0]);
      line.setAttribute('y1', ep.left[1]);
      line.setAttribute('x2', ep.right[0]);
      line.setAttribute('y2', ep.right[1]);
      line.setAttribute('stroke', colour);
      line.setAttribute('stroke-width', '0.001');
      line.setAttribute('opacity', '0.5');
      svg.appendChild(line);
    }}

    // Label each of the N_LINES line boxes
    for (let i = 0; i < N_LINES; i++) {{
      const tMid = (dividerT[i] + dividerT[i + 1]) / 2;
      const ep = lineEndpoints(q, tMid);
      // Place label on outer edge of the column
      const isRightmost = (colNum === 1);
      const labelPt = isRightmost ? ep.right : ep.left;
      const nudge = isRightmost ? 0.012 : -0.012;
      const anchor = isRightmost ? 'start' : 'end';
      const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      label.setAttribute('x', labelPt[0] + nudge);
      label.setAttribute('y', labelPt[1] + 0.004);
      label.setAttribute('text-anchor', anchor);
      label.setAttribute('font-size', '0.009');
      label.setAttribute('fill', colour);
      label.textContent = String(i + 1);
      svg.appendChild(label);
    }}

    // Corner handles
    for (const corner of ['tl', 'tr', 'bl', 'br']) {{
      const [cx, cy] = q[corner];
      const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      circle.setAttribute('cx', cx);
      circle.setAttribute('cy', cy);
      circle.setAttribute('r', '0.008');
      circle.setAttribute('fill', handleFill);
      circle.setAttribute('stroke', '#fff');
      circle.setAttribute('stroke-width', '0.001');
      circle.setAttribute('class', 'handle');
      circle.dataset.col = colName;
      circle.dataset.corner = corner;
      circle.addEventListener('mouseenter', () => circle.setAttribute('r', '0.012'));
      circle.addEventListener('mouseleave', () => circle.setAttribute('r', '0.008'));
      svg.appendChild(circle);

      // Corner label
      const cLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      const lx = corner.includes('l') ? cx - 0.015 : cx + 0.015;
      const ly = corner.includes('t') ? cy - 0.012 : cy + 0.018;
      const la = corner.includes('l') ? 'end' : 'start';
      cLabel.setAttribute('x', lx);
      cLabel.setAttribute('y', ly);
      cLabel.setAttribute('text-anchor', la);
      cLabel.setAttribute('font-size', '0.009');
      cLabel.setAttribute('fill', '#fff');
      cLabel.setAttribute('opacity', '0.5');
      cLabel.textContent = `C${{colNum}} ${{corner.toUpperCase()}}`;
      svg.appendChild(cLabel);
    }}

    // Edge midpoint handles
    const edges = [
      {{ name: 'top',    corners: ['tl', 'tr'] }},
      {{ name: 'bottom', corners: ['bl', 'br'] }},
      {{ name: 'left',   corners: ['tl', 'bl'] }},
      {{ name: 'right',  corners: ['tr', 'br'] }},
    ];
    for (const edge of edges) {{
      const [c1, c2] = edge.corners;
      const mx = (q[c1][0] + q[c2][0]) / 2;
      const my = (q[c1][1] + q[c2][1]) / 2;
      const rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
      const rw = 0.016, rh = 0.011;
      rect.setAttribute('x', mx - rw / 2);
      rect.setAttribute('y', my - rh / 2);
      rect.setAttribute('width', rw);
      rect.setAttribute('height', rh);
      rect.setAttribute('rx', '0.002');
      rect.setAttribute('fill', handleFill);
      rect.setAttribute('stroke', '#fff');
      rect.setAttribute('stroke-width', '0.0008');
      rect.setAttribute('opacity', '0.7');
      rect.setAttribute('class', 'handle');
      rect.dataset.col = colName;
      rect.dataset.edge = edge.name;
      rect.dataset.corners = edge.corners.join(',');
      rect.addEventListener('mouseenter', () => rect.setAttribute('opacity', '1'));
      rect.addEventListener('mouseleave', () => rect.setAttribute('opacity', '0.7'));
      svg.appendChild(rect);
    }}

    // Center handle
    const cx = (q.tl[0] + q.tr[0] + q.bl[0] + q.br[0]) / 4;
    const cy = (q.tl[1] + q.tr[1] + q.bl[1] + q.br[1]) / 4;
    const cRect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
    const cw = 0.020, ch = 0.014;
    cRect.setAttribute('x', cx - cw / 2);
    cRect.setAttribute('y', cy - ch / 2);
    cRect.setAttribute('width', cw);
    cRect.setAttribute('height', ch);
    cRect.setAttribute('rx', '0.003');
    cRect.setAttribute('fill', handleFill);
    cRect.setAttribute('stroke', '#fff');
    cRect.setAttribute('stroke-width', '0.001');
    cRect.setAttribute('opacity', '0.5');
    cRect.setAttribute('class', 'handle');
    cRect.dataset.col = colName;
    cRect.dataset.edge = 'center';
    cRect.dataset.corners = 'tl,tr,bl,br';
    cRect.addEventListener('mouseenter', () => cRect.setAttribute('opacity', '0.9'));
    cRect.addEventListener('mouseleave', () => cRect.setAttribute('opacity', '0.5'));
    svg.appendChild(cRect);

    // Column label
    const midX = (q.tl[0] + q.tr[0]) / 2;
    const topY = Math.min(q.tl[1], q.tr[1]) - 0.02;
    const colLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
    colLabel.setAttribute('x', midX);
    colLabel.setAttribute('y', topY);
    colLabel.setAttribute('text-anchor', 'middle');
    colLabel.setAttribute('font-size', '0.016');
    colLabel.setAttribute('font-weight', 'bold');
    colLabel.setAttribute('fill', colour);
    colLabel.textContent = `Column ${{colNum}}`;
    svg.appendChild(colLabel);
  }});
}}

// Dragging
let dragInfo = null;

function getSvgCoords(e) {{
  const rect = svg.getBoundingClientRect();
  return [
    (e.clientX - rect.left) / rect.width,
    (e.clientY - rect.top) / rect.height,
  ];
}}

svg.addEventListener('mousedown', (e) => {{
  const el = e.target;
  if (!el.classList.contains('handle')) return;
  e.preventDefault();
  const col = el.dataset.col;
  const [mx, my] = getSvgCoords(e);

  let corners;
  if (el.dataset.corner) {{
    corners = [el.dataset.corner];
  }} else if (el.dataset.corners) {{
    corners = el.dataset.corners.split(',');
  }} else {{
    return;
  }}

  const startPts = {{}};
  for (const c of corners) {{
    startPts[c] = [...cols[col][c]];
  }}

  dragInfo = {{
    col,
    corners,
    startPts,
    startMouse: [mx, my],
    el,
    edge: el.dataset.edge || null,
  }};
  el.classList.add('dragging');
}});

window.addEventListener('mousemove', (e) => {{
  if (!dragInfo) return;
  e.preventDefault();
  const [mx, my] = getSvgCoords(e);
  let dx = mx - dragInfo.startMouse[0];
  let dy = my - dragInfo.startMouse[1];
  if (fineMode) {{ dx *= FINE_SCALE; dy *= FINE_SCALE; }}

  // Constrain side handles to x-only, top/bottom handles to y-only
  if (dragInfo.edge === 'left' || dragInfo.edge === 'right') dy = 0;
  if (dragInfo.edge === 'top' || dragInfo.edge === 'bottom') dx = 0;

  for (const c of dragInfo.corners) {{
    cols[dragInfo.col][c] = [
      dragInfo.startPts[c][0] + dx,
      dragInfo.startPts[c][1] + dy,
    ];
  }}

  drawAll();
  const handles = svg.querySelectorAll('.handle');
  for (const h of handles) {{
    const match = dragInfo.edge
      ? (h.dataset.col === dragInfo.col && h.dataset.edge === dragInfo.edge)
      : (h.dataset.col === dragInfo.col && h.dataset.corner === dragInfo.corners[0]);
    if (match) {{
      h.classList.add('dragging');
      dragInfo.el = h;
      break;
    }}
  }}
  updateStatus();
}});

window.addEventListener('mouseup', () => {{
  if (dragInfo) {{
    dragInfo.el.classList.remove('dragging');
    activeCol = dragInfo.col;
    activeCorners = dragInfo.corners;
    updateStatus();
    dragInfo = null;
  }}
}});

// Keyboard nudge
let activeCol = 'col1';
let activeCorners = ['tl'];

window.addEventListener('keydown', (e) => {{
  const step = fineMode ? 0.001 : 0.005;
  const k = e.key;

  if (k === 'f' || k === 'F') {{
    toggleFine();
    return;
  }}

  if (k === 'Tab') {{
    e.preventDefault();
    const corners = ['tl', 'tr', 'bl', 'br'];
    const colKeys = Object.keys(cols);
    let ci = corners.indexOf(activeCorners[0]);
    ci++;
    if (ci >= corners.length) {{
      ci = 0;
      const colIdx = colKeys.indexOf(activeCol);
      activeCol = colKeys[(colIdx + 1) % colKeys.length];
    }}
    activeCorners = [corners[ci]];
    updateStatus();
    return;
  }}

  let dx = 0, dy = 0;
  if (k === 'ArrowLeft') dx = -step;
  else if (k === 'ArrowRight') dx = step;
  else if (k === 'ArrowUp') dy = -step;
  else if (k === 'ArrowDown') dy = step;
  else return;

  e.preventDefault();
  for (const ac of activeCorners) {{
    const pt = cols[activeCol][ac];
    pt[0] += dx;
    pt[1] += dy;
  }}
  drawAll();
  updateStatus();
}});

function updateStatus() {{
  const q = cols[activeCol];
  const labels = activeCorners.map(c => c.toUpperCase()).join('+');
  const pt = q[activeCorners[0]];
  const colNum = Object.keys(cols).indexOf(activeCol) + 1;
  statusEl.textContent = `Active: col${{colNum}} ${{labels}} (${{(pt[0]).toFixed(4)}}, ${{(pt[1]).toFixed(4)}}) | Arrow keys to nudge, Tab to cycle`;
}}

// Export
function exportJSON() {{
  const round4 = (v) => Math.round(v * 10000) / 10000;
  const toPx = ([rx, ry]) => [Math.round(rx * IMG_W), Math.round(ry * IMG_H)];

  const result = {{
    page: PAGE,
    image_size: [IMG_W, IMG_H],
    columns: {{}},
  }};

  for (const [colName, q] of Object.entries(cols)) {{
    result.columns[colName] = {{
      rel: {{
        tl: [round4(q.tl[0]), round4(q.tl[1])],
        tr: [round4(q.tr[0]), round4(q.tr[1])],
        bl: [round4(q.bl[0]), round4(q.bl[1])],
        br: [round4(q.br[0]), round4(q.br[1])],
      }},
      px: {{
        tl: toPx(q.tl),
        tr: toPx(q.tr),
        bl: toPx(q.bl),
        br: toPx(q.br),
      }},
    }};
  }}

  const jsonStr = JSON.stringify(result, null, 2) + '\\n';
  const blob = new Blob([jsonStr], {{type: 'application/json'}});
  const a = document.createElement('a');
  a.download = 'column-coordinates-' + PAGE + '.json';
  a.href = URL.createObjectURL(blob);
  a.click();
  URL.revokeObjectURL(a.href);
}}

// Init
drawAll();
updateStatus();
</script>
</body>
</html>
"""

    OUT_DIR.mkdir(exist_ok=True)
    out_path = OUT_DIR / f"quad-editor-{page_id}.html"
    out_path.write_text(html, encoding="utf-8", newline="")
    print(f"Editor written to: {out_path}")

    # Serve from repo root so both .novc/ HTML and aleppo-pages/ are accessible
    serve_and_open(ac_paths.ac_data_root(), f".novc/quad-editor-{page_id}.html")


def main():
    if len(sys.argv) < 2:
        print("Usage: python py_ac_loc/gen_col_quad_editor.py <page_id> [ncols]")
        print("  e.g.: python py_ac_loc/gen_col_quad_editor.py 270r")
        print("        python py_ac_loc/gen_col_quad_editor.py 001v 3")
        sys.exit(1)
    page_id = sys.argv[1]
    ncols = int(sys.argv[2]) if len(sys.argv) > 2 else 2
    if ncols not in (1, 2, 3):
        print(f"Error: ncols must be 1, 2, or 3, got {ncols}")
        sys.exit(1)
    generate_editor(page_id, ncols)


if __name__ == "__main__":
    main()
